# Github Action Workflow
name: chat-app
on:
  push:
    paths:
      - '!README.md'
    branches:
      - dev
      - main
  pull_request:
    branches: 
      - dev
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint